### PR TITLE
Getting Started with BBB, blog

### PR DESCRIPTION
**Pull request by robodhruv**
Do let me know if any changes are required. It should be able to merge safely, without any changes!

### CODE REVIEW

**Comment by darshan3** [comment]
there are some conflicts. please resolve them

**Comment by robodhruv** [comment]
I have pulled the repo again.. I dont see any conflicts

**Comment by darshan3** [comment]
there are some changes in file 2016-03-24-meanshift-algorithm-for-image-processing.md

**Comment by udiboy1209** [comment]
Firstly remove the change you have made for `2016-03-24-meanshift-algorithm-for-image-processing.md` from the commit. And you have added a `md~` gedit backup file too. Remove that too.

I guess this command should help you

```
git reset --soft HEAD^1
git checkout -- 2016-03-24-meanshift-algorithm-for-image-processing.md 2016-04-26-getting-started-with-beaglebone-black.md~
git commit
git push -f
```

**Comment by udiboy1209** [comment]
Merged in [96e6d0](https://github.com/elec-club-iitb/elec-club-iitb.github.io/commit/96e6d0e7a00cd636a366c2dcb70ddd0a064c1ecc). Thanks :tada: !

**Pull request closed without merging**
